version: '3.9'

services:
      server:
       image: 'abhay2209/docker-nodeapp'
       ports:
        - '3000:3000'
      db:
        image: 'postgres'
        ports: 
           - '5432:5432'
        environment:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'admin'
          POSTGRES_DB: 'notes'
        volumes:
          - ./start.sql:/docker-entrypoint-initdb.d/start.sql

